# Generated by Django 4.1.5 on 2023-03-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "course_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCQ_WEEK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week",
                    models.CharField(
                        choices=[
                            ("1", "First"),
                            ("2", "Second"),
                            ("3", "Third"),
                            ("4", "Four"),
                            ("5", "Five"),
                            ("6", "Six"),
                            ("7", "Seven"),
                            ("8", "Eight"),
                            ("9", "Nine"),
                            ("10", "Ten"),
                            ("11", "Eleven"),
                            ("12", "Twelve"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCQNums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mcq_num", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="SessionYearModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_start_year", models.DateField()),
                ("session_end_year", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("section", models.CharField(max_length=4)),
                ("email", models.CharField(default="no email", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.courses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YearSemester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[("ONE", "One"), ("TWO", "Two"), ("THREE", "Three")],
                        max_length=15,
                    ),
                ),
                (
                    "sem",
                    models.CharField(
                        choices=[("FIRST", "First"), ("SECOND", "Second")],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=255)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.courses"
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.yearsemester",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Studentresult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "mcq_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.mcqnums"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.student"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.subjects"
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="home.mcq_week",
                    ),
                ),
                (
                    "year_sem",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.yearsemester",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="year_sem",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.yearsemester",
            ),
        ),
    ]
