# Generated by Django 4.1.5 on 2023-02-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default='no email', max_length=100),
        ),
    ]
