# Generated by Django 4.1.5 on 2023-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_studentresult_year_sem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcq_week",
            name="week",
            field=models.CharField(
                choices=[
                    ("1", "First"),
                    ("2", "Second"),
                    ("3", "Third"),
                    ("4", "Four"),
                    ("5", "Five"),
                    ("6", "Six"),
                    ("7", "Seven"),
                    ("8", "Eight"),
                    ("9", "Nine"),
                    ("10", "Ten"),
                    ("11", "Eleven"),
                    ("12", "Twelve"),
                ],
                max_length=20,
            ),
        ),
    ]
