# Generated by Django 4.1.5 on 2023-02-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_studentresult_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ_WEEK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('THIRD', 'Third'), ('FOUR', 'Four'), ('FIVE', 'FiVE'), ('SIX', 'Six'), ('SEVEN', 'Seven'), ('EIGHT', 'Eight'), ('NINE', 'Nine'), ('TEN', 'Ten'), ('ELEVEN', 'Eleven'), ('TWELVE', 'Twelve')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.mcq_week'),
        ),
    ]
